

nouns_dict = {
    'the air': ('air', 'airs', 'ar', 'ares'),
    'the area': ('area', 'areas', 'área', 'áreas'),
    'the art': ('art', 'arts', 'arte', 'artes'),
    'the body': ('body', 'bodies', 'corpo', 'corpos'),
    'the book': ('book', 'books', 'livro', 'livros'),
    'the business': ('business', 'businesses', 'negócios', 'os negócios'),
    'the car': ('car', 'cars', 'carro ', 'carros'),
    'the change': ('change', 'changes', 'mudança', 'mudanças'),
    'the child': ('child', 'children', 'criança', 'crianças'),
    'the city': ('city', 'cities', 'cidade', 'cidades'),
    'the community': ('community', 'communities', 'comunidade', 'comunidades'),
    'the company': ('company', 'companies', 'empresa', 'empresas'),
    'the country': ('country', 'countries', 'país', 'países'),
    'the day': ('day', 'days', 'dia', 'dias'),
    'the door': ('door', 'doors', 'porta', 'portas'),
    'the ending': ('ending', 'endings', 'final', 'finais'),
    'the eye': ('eye', 'eyes', 'olho', 'olhos'),
    'the face': ('face', 'faces', 'rosto', 'rostos'),
    'the fact': ('fact', 'facts', 'fato', 'fatos'),
    'the family': ('family', 'families', 'família', 'famílias'),
    'the father': ('father', 'fathers', 'pai', 'pais'),
    'the strength': ('strength', 'strengths', 'força', 'forças'),
    'the friend': ('friend', 'friends', 'amigo', 'amigos'),
    'the game': ('game', 'games', 'jogo', 'jogos'),
    'the girl': ('girl', 'girls', 'menina', 'meninas'),
    'the government': ('government', 'governments', 'governo', 'governos'),
    'the group': ('group', 'groups', 'grupo', 'grupos'),
    'the guy': ('guy', 'guys', 'cara', 'pessoal'),
    'the hand': ('hand', 'hands', 'mão', 'mãos'),
    'the head': ('head', 'heads', 'cabeça', 'cabeças'),
    'the history': ('history', 'histories', 'história', 'histórias'),
    'the home': ('home', 'homes', 'casa', 'casas'),
    'the hour': ('hour', 'hours', 'hora', 'horas'),
    'the house': ('house', 'houses', 'casa', 'casas'),
    'the idea': ('idea', 'ideas', 'ideia', 'ideias'),
    'the issue': ('issue', 'issues', 'problema', 'problemas'),
    'the job': ('job', 'jobs', 'emprego', 'empregos'),
    'the kid': ('kid', 'kids', 'criança', 'crianças'),
    'the kind': ('kind', 'kinds', 'tipo', 'tipos'),
    'the law': ('law', 'laws', 'lei', 'leis'),
    'the level': ('level', 'levels', 'nível', 'níveis'),
    'the life': ('life', 'lifes', 'vida', 'vidas'),
    'the line': ('line', 'lines', 'linha', 'linhas'),
    'the man': ('man', 'men', 'homem', 'homens'),
    'the member': ('member', 'members', 'membro', 'membros'),
    'the minute': ('minute', 'minutes', 'minuto', 'minutos'),
    'the moment': ('moment', 'moments', 'momento', 'momentos'),
    'the month': ('month', 'months', 'mês', 'meses'),
    'the morning': ('morning', 'mornings', 'manhã', 'manhãs'),
    'the mother': ('mother', 'mothers', 'mãe', 'mães'),
    'the name': ('name', 'names', 'nome', 'nomes'),
    'the night': ('night', 'nights', 'noite', 'noites'),
    'the number': ('number', 'numbers', 'número', 'números'),
    'the office': ('office', 'offices', 'escritório', 'escritórios'),
    'the other': ('other', 'others', 'outro(a)', 'outros(as)'),
    'the parent': ('parent', 'parents', 'pai', 'pais'),
    'the part': ('part', 'parts', 'parte', 'partes'),
    'the party': ('party', 'parties', 'festa', 'festas'),
    'the person': ('person', 'people', 'pessoa', 'pessoas'),
    'the piece of information': ('piece of information', 'pieces of information', 'informação', 'informações'),
    'the place': ('place', 'places', 'lugar', 'lugares'),
    'the point': ('point', 'points', 'ponto', 'pontos'),
    'the power': ('power', 'powers', 'poder', 'poderes'),
    'the president': ('president', 'presidents', 'presidente', 'presidentes'),
    'the problem': ('problem', 'problems', 'problema', 'problemas'),
    'the program': ('program', 'programs', 'programa', 'programas'),
    'the question': ('question', 'questions', 'questão', 'questões'),
    'the reason': ('reason', 'reasons', 'razão', 'razões'),
    'the research': ('research', 'researches', 'pesquisa', 'pesquisas'),
    'the result': ('result', 'results', 'resultado', 'resultados'),
    'the right': ('right', 'rights', 'direito', 'direitos'),
    'the room': ('room', 'rooms', 'quarto', 'quartos'),
    'the school': ('school', 'schools', 'escola', 'escolas'),
    'the service': ('service', 'services', 'serviço', 'serviços'),
    'the side': ('side', 'sides', 'lado', 'lados'),
    'the state': ('state', 'states', 'estado', 'estados'),
    'the story': ('story', 'stories', 'história', 'histórias'),
    'the student': ('student', 'students', 'estudante', 'estudantes'),
    'the study': ('study', 'studies', 'estudo', 'estudos'),
    'the system': ('system', 'systems', 'sistema', 'sistemas'),
    'the teacher': ('teacher', 'teachers', 'professor(a)', 'professores'),
    'the team': ('team', 'teams', 'equipe', 'equipes'),
    'the thing': ('thing', 'things', 'coisa', 'coisas'),
    'the time': ('time', 'times', 'tempo', 'tempos'),
    'the war': ('war', 'wars', 'guerra', 'guerras'),
    'the water': ('water', 'waters', 'água', 'águas'),
    'the way': ('way', 'ways', 'caminho', 'caminhos'),
    'the week': ('week', 'weeks', 'semana', 'semanas'),
    'the woman': ('woman', 'women', 'mulher', 'mulheres'),
    'the word': ('word', 'words', 'palavra', 'palavras'),
    'the work': ('work', 'works', 'trabalho', 'trabalhos'),
    'the world': ('world', 'worlds', 'mundo', 'mundos'),
    'the year': ('year', 'years', 'ano', 'anos')
}

nouns_dict_keys = [word for word in nouns_dict]

nouns_dict_values = [word for word in nouns_dict.values()]

nouns = [
    'air', 'airs',
    'area', 'areas',
    'art', 'arts',
    'body', 'bodies',
    'book', 'books',
    'business', 'businesses',
    'car', 'cars',
    'change', 'changes',
    'child', 'children',
    'city', 'cities',
    'community', 'communities',
    'company', 'companies',
    'country', 'countries',
    'day', 'days',
    'door', 'doors',
    'ending', 'endings',
    'eye', 'eyes',
    'face', 'faces',
    'fact', 'facts',
    'family', 'families',
    'father', 'fathers',
    'strength', 'strengths',
    'friend', 'friends',
    'game', 'games',
    'girl', 'girls',
    'government', 'governments',
    'group', 'groups',
    'guy', 'guys',
    'hand', 'hands',
    'head', 'heads',
    'history', 'histories',
    'home', 'homes',
    'hour', 'hours',
    'house', 'houses',
    'idea', 'ideas',
    'issue', 'issues',
    'job', 'jobs',
    'kid', 'kids',
    'kind', 'kinds',
    'law', 'laws',
    'level', 'levels',
    'life', 'lifes',
    'line', 'lines',
    'man', 'men',
    'member', 'members',
    'minute', 'minutes',
    'moment', 'moments',
    'month', 'months',
    'morning', 'mornings',
    'mother', 'mothers',
    'name', 'names',
    'night', 'nights',
    'number', 'numbers',
    'office', 'offices',
    'other', 'others',
    'parents',
    'part', 'parts',
    'party', 'parties',
    'person', 'people',
    'piece of information', 'pieces of information',
    'place', 'places',
    'point', 'points',
    'power', 'powers',
    'president', 'presidents',
    'problem', 'problems',
    'program', 'programs',
    'question', 'questions',
    'reason', 'reasons',
    'research', 'researches',
    'result', 'results',
    'right', 'rights',
    'room', 'rooms',
    'school', 'schools',
    'service', 'services',
    'side', 'sides',
    'state', 'states',
    'story', 'stories',
    'student', 'students',
    'study', 'studies',
    'system', 'systems',
    'teacher', 'teachers',
    'team', 'teams',
    'thing', 'things',
    'time', 'times',
    'war', 'wars',
    'water', 'waters',
    'way', 'ways',
    'week', 'weeks',
    'woman', 'women',
    'word', 'words',
    'work', 'works',
    'world', 'worlds',
    'year', 'years'
]

nouns_pt_br = [
    'ar', 'ares',
    'área', 'áreas',
    'arte', 'artes',
    'corpo', 'corpos',
    'livro', 'livros',
    'negócios', 'os negócios',
    'carro ', 'carros',
    'mudança', 'mudanças',
    'criança', 'crianças',
    'cidade', 'cidades',
    'comunidade', 'comunidades',
    'empresa', 'empresas',
    'país', 'países',
    'dia', 'dias',
    'porta', 'portas',
    'final', 'finais',
    'olho', 'olhos',
    'rosto', 'rostos',
    'fato', 'fatos',
    'família', 'famílias',
    'pai', 'pais',
    'força', 'forças',
    'amigo', 'amigos',
    'jogo', 'jogos',
    'menina', 'meninas',
    'governo', 'governos',
    'grupo', 'grupos',
    'cara', 'pessoal',
    'mão', 'mãos',
    'cabeça', 'cabeças',
    'história', 'histórias',
    'casa', 'casas',
    'hora', 'horas',
    'casa', 'casas',
    'ideia', 'ideias',
    'problema', 'problemas',
    'emprego', 'empregos',
    'criança', 'crianças',
    'tipo', 'tipos',
    'lei', 'leis',
    'nível', 'níveis',
    'vida', 'vidas',
    'linha', 'linhas',
    'homem', 'homens',
    'membro', 'membros ',
    'minuto', 'minutos',
    'momento', 'momentos',
    'mês', 'meses',
    'manhã', 'manhãs',
    'mãe', 'mães',
    'nome', 'nomes',
    'noite', 'noites',
    'número', 'números',
    'escritório', 'escritórios',
    'outro(a)', 'outros(as)',
    'pais',
    'parte', 'partes',
    'festa', 'festas',
    'pessoa', 'pessoas',
    'pedaço de informação', 'pedaços de informação',
    'lugar', 'lugares',
    'ponto', 'pontos',
    'poder', 'poderes',
    'presidente', 'presidentes',
    'problema', 'problemas',
    'programa', 'programas',
    'questão', 'questões',
    'razão', 'razões',
    'pesquisa', 'pesquisas',
    'resultado', 'resultados',
    'direito', 'direitos',
    'quarto', 'quartos',
    'escola', 'escolas',
    'serviço', 'serviços',
    'lado', 'lados',
    'estado', 'estados',
    'história', 'histórias',
    'estudante', 'estudantes',
    'estudo', 'estudos',
    'sistema', 'sistemas',
    'professor(a)', 'professores',
    'equipe', 'equipes',
    'coisa', 'coisas',
    'tempo', 'tempos',
    'guerra', 'guerras',
    'água', 'águas',
    'caminho', 'caminhos',
    'semana', 'semanas',
    'mulher', 'mulheres',
    'palavra', 'palavras',
    'trabalho', 'trabalhos',
    'mundo', 'mundos',
    'ano', 'anos'
]


if __name__ == '__main__':
    print('\n')
    print(f"{len(nouns_dict) = }")
